### PR TITLE
Swift 2.0 support ( Include XCode7 Beta 4)

### PR DESCRIPTION
**Pull request by pepicrft**
- [x] Migrated Swift syntax to fix some Swift 2 related issues.
- [x] Added extra capture method to capture `ErrorType` Swift error types
- [x] Updated version number to 0.2.2

### CODE REVIEW

**Comment by eriksargent** [comment]
I believe (although I haven't researched it much) that swift 2 makes it possible to capture unhandled exceptions. Currently, it is not possible in swift, so we are required to have this ugly piece of objective c code to capture and log them. It would be nice if we can remove that and exclusively use swift instead.

**Comment by eriksargent** [comment]
We should also probably merge this into a `swift2` branch instead of master until swift 2 is released

**Comment by pepicrft** [comment]
Hello @eriksargent , makes sense adding the swift2 branch instead. Regarding the unhandled exceptions capturing right now if not possible in Swift so they only way right now as you say is keeping that piece of Objective-C code :S.

**Comment by hankbao** [comment]
iOS 9 will be released today. Do you have any ETA about this?

**Comment by pepicrft** [comment]
:tada:

**Pull request merged**
