### PR TITLE
Bulk Updates

### PR DESCRIPTION
**Pull request by remaerd**
Hello, I make the following changes.
- Swift 1.2 Support
- Dynamic Frameworks for iOS / OS X
- Carthage Supports

### CODE REVIEW

**Comment by asbjornu** [comment]
For the future, I can say it would be easier to review the pull request if you had made more than one commit. Each commit should be as simple and small as possible, with a good, clear description of what it does. Secondly, it's a good idea to create a branch and then make the pull request from it (instead of master), since now, if you make any commits to master and push those, they will end up in this pull request, which makes the merge a bit harder.

When it comes to the content of the pull request, I don't fully understand what it does, so perhaps @timorzadir can take a look at it and see if this is something we should pull and merge.

**Comment by timorzadir** [comment]
Since Swift 1.2 is still in beta, perhaps you can submit a separate PR with the _Dynamics Frameworks_ and _Carthage Support_ ?

**Comment by remaerd** [comment]
I'm already using Swift 1.2 and I cannot create Swift 1.1 or 1.0 frameworks. Raven-Swift is not a widely used framework, and 1.2 is way more stable than previous versions. So I think it safe to make those changes.

**Comment by dcharbonnier** [comment]
1.2 is not beta anymore

**Pull request merged**
